[Settings]

#Layout
opacity = 80
timer_x = 125
timer_y = 120
table_x = 2112
table_y = 8
timer_x_2 = 0
timer_y_2 = 0
table_x_2 = 0
table_y_2 = 0
table_align = right
table_visible = 1
ai_count_visible = 0

#Font
timer_font_size = 16
label_font_size = 15
timer_font_color = lightcyan
timer_font_color_while_running = khaki
timer_font_color_ex = thistle
ai_count_font_color = white
outline_color = #101010

#Sound
play_start_sound = true
play_record_sound = true
play_activation_sound = true
sound_volume = 40
sound_delay = 3250

#Hotkey
start_key = f12
log_key = insert
log_key_ex = delete
log_key_loop = home
log_key_loopB = end
increment_key = page up
decrement_key = page down
ai_count_key_2 = f7
ai_count_key_3 = f8
sheet_switch_key = f9
preset_switch_key = ctrl+shift+tab
reset_position_key = ctrl+shift+r


[Preset1]
name = ルベランギス3
table_file = ルベランギス3.xlsx

initial_time = 09:59
activation_normal = 60000
activation_ex  = 60000
activation_loopA  = 5000
activation_loopB  = 6000
loopA_time = 23500,21000
loopB_time = 22200,24500

log_label = 
log_label_ex = 
loopA_labels = 1 線上\nR90_A1.png,2 線上(遅)\nR90_A2.png,3 金網\nR90_B.png,4 線上(遅)\nR90_A1.png,5 外周\nR90_C.png,6 金網(遅)\nR90_B.png
loopB_labels = 1 虹床,2 外周\nR25_A.png,3 虹床,4 外周\nR25_B.png,5 虹床,6 なし\nR25_C.png,7 虹床,8 線上\nR25_D.png,9 虹床,10 金網\nR25_E.png,11 虹床,12 線外\nR25_F.png


[Preset2]
name = デルメゼ4
table_file = デルメゼ4.xlsx

initial_time = 19:59
activation_normal = 108500
activation_ex  = 60000
activation_loopA  = 5000
activation_loopB  = 6000
loopA_time = 14550
loopB_time = 12550

log_label = 
log_label_ex = 
loopA_labels = 
loopB_labels = 


[Preset3]
name = シドー
table_file = シドー.xlsx

initial_time = 09:59
activation_normal = 0
activation_ex = 0
activation_loopA = 6000
activation_loopB = 6000
loopA_time = 14500
loopB_time = 12500
loopA_stop_time = 60000
loopB_stop_time = 90000

log_label =
log_label_ex =
loopA_labels =
loopB_labels =